// BackEnd/Client/src/Components/Login.tsx
import React, { useState } from "react";
import { LOGIN_TO_SYSTEM } from "../GraphQL/Mutations";
import { useMutation } from "@apollo/client";
import {useNavigate} from "react-router-dom";
import jwt_decode from "jwt-decode";

function Login() {
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");

    const [loginCompany, { error }] = useMutation(LOGIN_TO_SYSTEM,{
        onCompleted({ loginCompany }) {
            sessionStorage.setItem("Authorization", "Bearer " + loginCompany.accessToken);
            sessionStorage.setItem("title", jwt_decode(loginCompany.accessToken).title);
            sessionStorage.setItem("companyId", jwt_decode(loginCompany.accessToken).companyId);
            // @ts-ignore
            window.location = '/products';
        }
    });

    const loginToSystem = () => {
        loginCompany({
            variables: {
                email: email,
                password: password,
            },
        },).then(r => console.log(r));

        if (error) {
            console.log(error);
        }

    }
    const navigate = useNavigate();

    const onSubmit = (event: { preventDefault: () => void; }) => {
        event.preventDefault();
    };

    return (
        <div className="flex items-center justify-center h-screen bg-gray-400">
            <div className="bg-black flex flex-col w-80 rounded-lg px-8 py-10">
                <div className="text-white mt-10">
                    <h1 className="font-poppins-bold text-4xl">Welcome Ricoma!</h1>
                    <p className="font-poppins-light pt-5">Let's login!</p>
                </div>
                <form onSubmit={onSubmit}
                    className="flex flex-col space-y-8 mt-10">
                <input
                    type="text"
                    placeholder="Email"
                    className="shadow-lg rounded-md focus:ring-0 p-2 border-0"
                    onChange={(e) => {
                        setEmail(e.target.value);
                    }}
                />
                <input
                    type="password"
                    placeholder="Password"
                    className="shadow-lg rounded-md onFocus:ring-0 p-2 border-0 mt-3"
                    onChange={(e) => {
                        setPassword(e.target.value);
                    }}
                />
                <button
                    onClick={loginToSystem}
                    className="font-poppins-extraBold text-white bg-checkBoxColor1 border border-[1px] border-headerBorderColor p-3 rounded-md shadow-lg mt-3">
                    Login
                </button>
                <p onClick={() => navigate(`/register`)}
                   className="font-poppins-light text-white text-[12px] cursor-pointer">Not Registered? Register.</p>
                </form>
            </div>
        </div>
    );
}

export default Login;

// FrontEnd/src/views/Login.vue
<script setup>

</script>

<template>
  <div class="flex items-center justify-center h-screen bg-headerBorderColor">
    <div class="bg-black flex flex-col w-80 rounded-lg px-8 py-10" style="background-image: url('/assets/images/backgroundImage.png')">
      <div class="text-white mt-10">
        <h1 class="font-poppins-bold text-4xl">Welcome Ricoma!</h1>
        <p class="font-poppins-light pt-5">Let's login!</p>
      </div>
      <form class="flex flex-col space-y-8 mt-10">
        <input type="text" placeholder="Email" class="shadow-lg rounded-md focus:ring-0 border-0">
        <input type="password" placeholder="Password" class="shadow-lg rounded-md focus:ring-0 border-0">
        <button class="font-poppins-extraBold text-white bg-checkBoxColor1 border border-[1px] border-headerBorderColor p-3 rounded-md shadow-lg">Login</button>
      </form>
    </div>
  </div>
  <!--
  <div class="flex flex-col space-y-4 min-w-screen h-screen animated fadeIn faster  fixed  left-0 top-0 flex justify-center items-center inset-0 z-50 outline-none focus:outline-none bg-gray-900">
  <div class="flex flex-col p-8 bg-bannerBackground shadow-md hover:shodow-lg rounded-2xl">
    <div class="flex items-center justify-between">
      <div class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg"
             class="w-16 h-16 rounded-2xl p-3 border border-gray-800 text-bannerBackground bg-white" fill="none"
             viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
        </svg>
        <div class="flex flex-col ml-3">
          <div class="font-medium leading-none text-white">Wrong Password</div>
          <p class="text-sm text-white leading-none mt-1">Please check your password.
          </p>
        </div>
      </div>
      <button  class="flex-no-shrink bg-red-500 px-5 ml-4 py-2 text-sm shadow-sm hover:shadow-lg font-medium tracking-wider border-2 border-red-500 text-white rounded-full">Okey</button>
    </div>
  </div>
  </div>
  -->
</template>
